# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - Versions/3*

pool:
  name: IATec-Builds-Agents-Linux

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '22.x'

  - task: Npm@1
    displayName: Install
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)'

  - task: Npm@1
    displayName: Build
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)'
      customCommand: 'run build-storybook"'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/storybook'
      ArtifactName: 'files'
      publishLocation: 'Container'      
